### ISSUE TITLE
Wont Connect to synology nas

### ISSUE THREAD

**Issue by stswilliams** [Garulf/Plexy#6]
Please type any relevant information here

I have synology nas 
1. So change to nas server
http://IP-address.admineName.direct.quickconnect.to:32400
2. If I get wrong keeps changing to local host (Please change this)
3. API token is not accepted 

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\susan\AppData\Roaming\FlowLauncher\Plugins\Plexy-2.0.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\susan\AppData\Roaming\FlowLauncher\Plugins\Plexy-2.0.0\lib\flox\__init__.py", line 134, in _context_menu
    self.context_menu(data)
  File "C:\Users\susan\AppData\Roaming\FlowLauncher\Plugins\Plexy-2.0.0\plugin\plexy.py", line 63, in context_menu
    key = data[0]
          ~~~~^^^
TypeError: 'NoneType' object is not subscriptable

```
</p>
</details>

**Comment by enoversum** [comment]
Similarly here. Have a Raspberry Pi behind a router, custom domain with https in place, which is working if accessed directly through a browser. The API token is also correct. But Plexy just won't connect and resets my connection info on the spot.

**Comment by Garulf** [comment]
Sorry, for some reason I did not get an alert for this issue. 

I'll look into it when I have the time.

**Comment by enoversum** [comment]
> Sorry, for some reason I did not get an alert for this issue.
> 
> I'll look into it when I have the time.

Wonderful! If you need any more info, please let me know. Happy to help!

**Comment by gitthangbaby** [comment]
Must be localhost HTTP, not HTTPS sadly. ShiftEnter doesn't show reset token item. Plugin address setting is not remembered, that's the global issue, each change must be followed by launcher restart.
